apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: price-whisper
  annotations:
    author: Gruppe 6 <philipp.borucki@stud.hs-flensburg.de | dorien.groenwald@stud.hs-flensburg.de | jannick.lindner@stud.hs-flensburg.de>
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003