apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
  namespace: price-whisper
  annotations:
    author: Gruppe 6 <philipp.borucki@stud.hs-flensburg.de | dorien.groenwald@stud.hs-flensburg.de | jannick.lindner@stud.hs-flensburg.de>
data:
  config.json: |
    [
      {
        "username": "username",
        "password": "changeMe!",
        "perms": [ "all" ]
      },
      {
        "username": "*",
        "perms": ["ready"]
      }
    ]