apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: price-whisper
  annotations:
    author: Gruppe 6 <philipp.borucki@stud.hs-flensburg.de | dorien.groenwald@stud.hs-flensburg.de | jannick.lindner@stud.hs-flensburg.de>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      initContainers:
        - name: wait-for-database
          image: busybox
          command: [ "/bin/sh", "-c" ]
          args: [ "until wget --spider -S http://database:4001/readyz 2>&1 | grep 'HTTP/1.1 200 OK'; do echo 'Waiting for RQLite...'; sleep 2; done;" ]
      containers:
        - name: products-container
          image: onyxmoon/pw-product-service:latest
          ports:
            - containerPort: 3003