apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: price-whisper
  annotations:
    author: Gruppe 6 <philipp.borucki@stud.hs-flensburg.de | dorien.groenwald@stud.hs-flensburg.de | jannick.lindner@stud.hs-flensburg.de>
data:
  proxyConfig.yaml: |
    proxy:
      listenAddress: 0.0.0.0:8080
      proxyRoutes:
        - name: User Service (User Info)
          context: /api/v1/user
          target: http://users:3001/api/v1/user
        - name: User Service (Login)
          context: /api/v1/authentication/login
          target: http://users:3001/api/v1/authentication/login
        - name: User Service (Registration)
          context: /api/v1/authentication/register
          target: http://users:3001/api/v1/authentication/register
        - name: Shoppinglist Service (Lists)
          context: /api/v1/shoppinglist
          target: http://shoppinglists:3002/api/v1/shoppinglist
        - name: Shoppinglist Service (Entries)
          context: /api/v1/shoppinglistentries
          target: http://shoppinglists:3002/api/v1/shoppinglistentries
        - name: Product Service (Products)
          context: /api/v1/product
          target: http://products:3003/api/v1/product
        - name: Product Service (Prices)
          context: /api/v1/price
          target: http://products:3003/api/v1/price
        - name: Web Service
          context: /
          target: http://web:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: price-whisper
  annotations:
    author: Gruppe 6 <philipp.borucki@stud.hs-flensburg.de | dorien.groenwald@stud.hs-flensburg.de | jannick.lindner@stud.hs-flensburg.de>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-config
      containers:
        - name: proxy-container
          image: onyxmoon/pw-http-proxy-service:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: proxy-config
              mountPath: /config
          env:
            - name: PROXY_CONFIG_PATH
              value: "/config/proxyConfig.yaml"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: price-whisper
  annotations:
    author: Gruppe 6 <philipp.borucki@stud.hs-flensburg.de | dorien.groenwald@stud.hs-flensburg.de | jannick.lindner@stud.hs-flensburg.de>
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080