apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: price-whisper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          image: onyxmoon/pw-web-service:latest
          ports:
            - containerPort: 3000