services:
  proxy:
    build:
      context: ./
      dockerfile: ./src/http-proxy-service/Dockerfile
    image: onyxmoon/pw-http-proxy-service:latest
    environment:
      - PROXY_CONFIG_PATH=./config/proxyConfig.docker.native.yaml
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - web
    networks:
      - public
      - internal

  web:
    build:
      context: ./
      dockerfile: ./src/web-service/Dockerfile
    image: onyxmoon/pw-web-service:latest
    ports:
      - 3000:3000
    depends_on:
      - products
      - shoppinglists
      - users
    networks:
      - internal

  products:
    build:
      context: ./
      dockerfile: ./src/product-service/Dockerfile
    image: onyxmoon/pw-product-service:latest
    ports:
      - 3003:3003
    networks:
      - internal

  users:
    build:
      context: ./
      dockerfile: ./src/user-service/Dockerfile
    image: onyxmoon/pw-user-service:latest
    ports:
      - 3001:3001
    networks:
      - internal

  shoppinglists:
    build:
      context: ./
      dockerfile: ./src/shoppinglist-service/Dockerfile
    image: onyxmoon/pw-shoppinglist-service:latest
    ports:
      - 3002:3002
    networks:
      - internal


networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true