version: "3.8"

services:
  proxy:
    image: onyxmoon/pw-http-proxy-service:latest
    environment:
      - PROXY_CONFIG_PATH=./config/proxyConfig.docker.yaml
    volumes:
      - ./src/http-proxy-service/config:/config
    ports:
      - 8080:8080
    depends_on:
      - web
    networks:
      - public
      - internal

  web:
    image: onyxmoon/pw-web-service:latest
    ports:
      - 3000:3000
    depends_on:
      - products
      - shoppinglists
      - users
    networks:
      - internal

  products:
    image: onyxmoon/pw-product-service:latest
    env_file:
      - ./src/product-service/.env
    ports:
      - 3003:3003
      - 50053:50053
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  users:
    image: onyxmoon/pw-user-service:latest
    env_file:
      - ./src/user-service/.env
    ports:
      - 3001:3001
      - 50051:50051
    volumes:
      - ./src/user-service/privateKey.pem:/privateKey.pem
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  shoppinglists:
    image: onyxmoon/pw-shoppinglist-service:latest
    env_file:
      - ./src/shoppinglist-service/.env
    ports:
      - 3002:3002
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy

  database:
    image: rqlite/rqlite:8.15.0
    ports:
      - "4001:4001"
    command: [ "-node-id", "1", "-auth", "/run/secrets/config.json", "-http-adv-addr", "database:4001" ]
    configs:
      - source: database
        target: config.json
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:4001/readyz || exit 1" ]
      interval: 5s
      retries: 5
      start_period: 30s
      start_interval: 1s

configs:
  database:
    content: |
      [
        {
          "username": "user",
          "password": "password",
          "perms": [ "all" ]
        },
        {
          "username": "*",
          "perms": ["ready"]
        }
      ]


networks:
  public:
    driver: bridge
  internal:
    driver: bridge
    internal: true