version: "3.8"

services:
  proxy:
    build:
      context: ./
      dockerfile: ./src/http-proxy-service/Dockerfile
    environment:
      - PROXY_CONFIG_PATH=./config/proxyConfig.docker.native.yaml
    ports:
      - "8080:8080"
    depends_on:
      - web

  web:
    build:
      context: ./
      dockerfile: ./src/web-service/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - products
      - shoppinglists
      - users

  products:
    build:
      context: ./
      dockerfile: ./src/product-service/Dockerfile
    ports:
      - "3003:3003"
      - "50053:50053"

  users:
    build:
      context: ./
      dockerfile: ./src/user-service/Dockerfile
    ports:
      - "3001:3001"
      - "50051:50051"

  shoppinglists:
    build:
      context: ./
      dockerfile: ./src/shoppinglist-service/Dockerfile
    ports:
      - "3002:3002"

  database:
    image: rqlite/rqlite:8.15.0
    ports:
      - "4001:4001"
      - "4002:4002"
    command: ["-auth", "/run/secrets/config.json"]
    configs:
      - source: database
        target: config.json

configs:
  database:
    content: |
      [
        {
          "username": "user",
          "password": "password",
          "perms": [ "all" ]
        }
      ]