services:
  proxy:
    build:
      context: ./
      dockerfile: ./src/http-proxy-service/Dockerfile
    image: onyxmoon/pw-http-proxy-service:latest
    ports:
      - 8080:8080
    depends_on:
      - web
    links:
      - web
  web:
    build:
      context: ./
      dockerfile: ./src/web-service/Dockerfile
    image: onyxmoon/pw-web-service:latest
    ports:
      - 3000:3000
    depends_on:
      - products
      - shoppinglists
      - users
    links:
      - products
      - shoppinglists
      - users

  products:
    build:
      context: ./
      dockerfile: ./src/product-service/Dockerfile
    image: onyxmoon/pw-product-service:latest
    ports:
      - 3003:3003

  users:
    build:
      context: ./
      dockerfile: ./src/user-service/Dockerfile
    image: onyxmoon/pw-user-service:latest
    ports:
      - 3001:3001

  shoppinglists:
    build:
      context: ./
      dockerfile: ./src/shoppinglist-service/Dockerfile
    image: onyxmoon/pw-shoppinglist-service:latest
    ports:
      - 3002:3002