services:
  proxy:
    build:
      context: ./
      dockerfile: ./src/http-proxy-service/Dockerfile
    environment:
      - PROXY_DOCKER_CONFIG_PATH=./config
      - PROXY_DOCKER_CONFIG_FILENAME=proxyConfig.docker.yaml
    ports:
      - 8080:8080
    depends_on:
      - lbweb
    networks:
      - dev-network

  lbweb:
    build:
      context: ./
      dockerfile: ./src/load-balancer-service/Dockerfile
    environment:
      - LOAD_BALANCER_CONFIG_PATH=./config/config.web-service.dev.yaml
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - products
      - shoppinglists
      - users
    networks:
      - dev-network

  products:
    build:
      context: ./
      dockerfile: ./src/product-service/Dockerfile
    ports:
      - 3003:3003
    networks:
      - dev-network

  users:
    build:
      context: ./
      dockerfile: ./src/user-service/Dockerfile
    ports:
      - 3001:3001
    networks:
      - dev-network

  shoppinglists:
    build:
      context: ./
      dockerfile: ./src/shoppinglist-service/Dockerfile
    ports:
      - 3002:3002
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network