apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-deployment
  namespace: price-whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products-container
          image: onyxmoon/pw-product-service:latest
          ports:
            - containerPort: 3003