apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  namespace: price-whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-container
          image: onyxmoon/pw-user-service:latest
          ports:
            - containerPort: 3001