services:
  load-balancer:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - IMAGE=onyxmoon/pw-web-service:latest
      - REPLICAS=5
      - NETWORK_NAME=bridge
    ports:
      - 3000:3000
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    network_mode: bridge
