phases:
    - targetrps: 0
      timeidx: 0
    - targetrps: 100
      timeidx: 15
    - targetrps: 500
      timeidx: 30
    - targetrps: 100
      timeidx: 50
    - targetrps: 0
      timeidx: 70
targets:
    - url: http://onyxmoon.me
users: 10
