name: Deploy to docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push:
    name: Build and push to docker hub registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push
        working-directory: ./
        run: |
          docker-compose build
          docker-compose -f docker-compose.push.yml push
